# Generated by Django 2.1.5 on 2022-04-22 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdb',
            name='id',
            field=models.AutoField(auto_created=True, default=123456789101112131415161718192021222324252627282930313233343536373839404142434445464748495051525354555657585960616263646566676869707172737475767778798081828384858687888990919293949596979899, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='salesdb',
            name='Item_Code',
            field=models.IntegerField(),
        ),
    ]
