# Generated by Django 2.1.5 on 2022-04-21 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='billSaleEntry',
            fields=[
                ('Item_Code', models.AutoField(primary_key=True, serialize=False)),
                ('Item_Name', models.CharField(max_length=500)),
                ('Item_Catogory', models.CharField(max_length=200)),
                ('HSN_Code', models.CharField(max_length=30)),
                ('Quatity_Bought', models.FloatField()),
                ('Rate_Of_Purchase', models.FloatField()),
                ('Unit', models.CharField(choices=[('PCS', 'PCS'), ('MTR', 'MTR'), ('CHK', 'CHK'), ('DOZ', 'DOZ'), ('JODA', 'JODA')], max_length=50)),
                ('Rate_Of_Sale', models.FloatField()),
                ('IGST_Percent', models.FloatField()),
                ('SGST_Percent', models.FloatField()),
                ('CGST_Percent', models.FloatField()),
                ('GST_Type', models.CharField(choices=[('Y', 'Yes'), ('N', 'No')], max_length=6)),
                ('Quatity_in_stock', models.FloatField()),
            ],
        ),
    ]
