# Generated by Django 2.1.5 on 2022-04-22 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminreport', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custdetail',
            name='GSTN_of_Customer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
